/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fpoly;

import javax.swing.ImageIcon;

/**
 *
 * @author hoang
 */
public class Menu extends javax.swing.JFrame {

    private QLSV qlsv;
    private QLDSV qldsv;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnQLSV = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnQLDSV = new javax.swing.JButton();
        tplMenu = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDangNhap = new javax.swing.JMenuItem();
        mnDangKy = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuQLSV = new javax.swing.JMenuItem();
        mnuQLDSV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnExit.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\Exit-icon.png")); // NOI18N
        btnExit.setText("Đăng Xuất");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(jSeparator1);

        btnQLSV.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\student-icon.png")); // NOI18N
        btnQLSV.setText("Quản Lý Sinh Viên");
        btnQLSV.setFocusable(false);
        btnQLSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLSV);
        jToolBar1.add(jSeparator2);

        btnQLDSV.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\icons8-ball-point-pen-32.png")); // NOI18N
        btnQLDSV.setText("Quản Lý Điểm Sinh Viên");
        btnQLDSV.setFocusable(false);
        btnQLDSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLDSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLDSV);

        jMenu1.setText("Hệ Thống");

        mnDangNhap.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\login-icon.png")); // NOI18N
        mnDangNhap.setText("Đăng Nhập");
        jMenu1.add(mnDangNhap);

        mnDangKy.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\Exit-icon.png")); // NOI18N
        mnDangKy.setText("Đăng Xuất");
        mnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangKyActionPerformed(evt);
            }
        });
        jMenu1.add(mnDangKy);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnuQLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQLSV.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\student-icon.png")); // NOI18N
        mnuQLSV.setText("Quản Lý Sinh Viên");
        mnuQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLSVActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQLSV);

        mnuQLDSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQLDSV.setIcon(new javax.swing.ImageIcon("D:\\Nhom 1_Agile_IT18101\\DuAnNhom1\\QuanLySinhVienNhom1\\img\\icons8-ball-point-pen-32.png")); // NOI18N
        mnuQLDSV.setText("Quản Lý Điểm Sinh Viên");
        mnuQLDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLDSVActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQLDSV);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLSVActionPerformed
        // TODO add your handling code here:
        if (qlsv == null) {
            qlsv = new QLSV();
            ImageIcon img = new ImageIcon(getClass().getResource("/img/icon/student-icon.png"));
            tplMenu.addTab("Quản Lý Sinh Viên", img, qlsv, "Quản Lý Sinh Viên");
        }
        tplMenu.setSelectedComponent(qlsv);

    }//GEN-LAST:event_mnuQLSVActionPerformed

    private void btnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVActionPerformed
        // TODO add your handling code here:
        if (qlsv == null) {
            qlsv = new QLSV();
            ImageIcon img = new ImageIcon(getClass().getResource("/img/icon/student-icon.png"));
            tplMenu.addTab("Quản Lý Sinh Viên", img, qlsv, "Quản Lý Sinh Viên");
        }
        tplMenu.setSelectedComponent(qlsv);
    }//GEN-LAST:event_btnQLSVActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnuQLDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLDSVActionPerformed
        // TODO add your handling code here:
        if (qldsv == null) {
            qldsv = new QLDSV();
            ImageIcon img = new ImageIcon(getClass().getResource("/img/icon/icons8-ball-point-pen-32.png"));
            tplMenu.addTab("Quản Lý Sinh Viên", img, qldsv, "Quản Lý Sinh Viên");
        }
        tplMenu.setSelectedComponent(qldsv);

    }//GEN-LAST:event_mnuQLDSVActionPerformed

    private void btnQLDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDSVActionPerformed
        // TODO add your handling code here:
        if (qldsv == null) {
            qldsv = new QLDSV();
            ImageIcon img = new ImageIcon(getClass().getResource("/img/icon/icons8-ball-point-pen-32.png"));
            tplMenu.addTab("Quản Lý Sinh Viên", img, qldsv, "Quản Lý Sinh Viên");
        }
        tplMenu.setSelectedComponent(qldsv);
    }//GEN-LAST:event_btnQLDSVActionPerformed

    private void mnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangKyActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQLDSV;
    private javax.swing.JButton btnQLSV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnDangKy;
    private javax.swing.JMenuItem mnDangNhap;
    private javax.swing.JMenuItem mnuQLDSV;
    private javax.swing.JMenuItem mnuQLSV;
    private javax.swing.JTabbedPane tplMenu;
    // End of variables declaration//GEN-END:variables
}
